### ISSUE TITLE
Feat: support 24bit sound?

### ISSUE THREAD

**Issue by quenbyako** [ebitengine/oto#131]
Linux [ALSA definetly providing](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gaa14b7f26877a812acbb39811364177f8) 24 bit values, but honestly i didn't work with alsa api, so i don't know how to properly implement it.

**Comment by hajimehoshi** [comment]
It is possible to support 24bit sound, but I don't plan to do that as I don't have bandwidth. PRs are welcome.

**Comment by ololosha228** [comment]
@hajimehoshi i can make PR, but i'm not sure that i contribute correctly, if i implement 24-bit supporting only in alsa driver, will you allow it?

**Comment by hajimehoshi** [comment]
It is great if you send a PR even only for Linux. I would want a PR to support multiple platforms ideally. If it is difficult to you too implement, I'll try later.

**Comment by hajimehoshi** [comment]
As Oto already supports 32bit floats, I think that's enough.
