### ISSUE TITLE
rename `UnplayedBufferSize` to `BufferedSize`

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/oto#197]
/CC @tinne26

**Comment by tinne26** [comment]
If this is going to be for v3, I think `UncommittedSamples` may also be an option, as it's independent from the actual sample size, whether it's S16 or F32 and mono or stereo.

I'll also point out that I'd rather use int64, not int. In 32-bit platforms, we have up to `2^32 = 4294967296 bytes`, which is `4294967296/ 4 = 1073741824 samples`, which at 48kHz is `1073741824/48000 ~= 22370 seconds`, which is only slightly above 6 hours. It's not hard to imagine people livestreaming longer than that, for example.

**Comment by hajimehoshi** [comment]
Oto is a low-level library so you don't have to touch this directly assuming you are using Ebitengine APIs.

**Comment by tinne26** [comment]
Just found out that SDL uses "QueuedAudioSize". Using "queued" instead of "uncommitted" may be worth considering.

**Comment by tinne26** [comment]
You changed the name, but it should be "queued", not "unqueued", as in: "data queued to be sent to the audio driver". Maybe it was a typo.

**Comment by hajimehoshi** [comment]
`UnplayedBufferSize` should return a buffer size that is not sent or queued to the driver, so `Unqueued*` sounds right.

**Comment by hajimehoshi** [comment]
'queued' still sounds confusing. queued-but-not-played-yet, right?

**Comment by hajimehoshi** [comment]
> Just found out that SDL uses "QueuedAudioSize". Using "queued" instead of "uncommitted" may be worth considering.

You mean https://wiki.libsdl.org/SDL2/SDL_GetQueuedAudioSize ?

Well, then 'queued' might be better.

**Comment by hajimehoshi** [comment]
So, as the term 'queue' is not used in Oto, I think I'll keep `UnplayedBufferSize`. @tinne26 Any thoughts?

**Comment by tinne26** [comment]
> This should be the set with https://wiki.libsdl.org/SDL2/SDL_QueueAudio so 'queued' might not be good for Oto.

Well, in Oto there's no explicit, user-invokable method for queueing audio, it's the player issuing the reads on the `io.Reader`. So, the `io.Read` method does the function of `SDL_QueueAudio` already.

I prefer the term "queued" as there are three stages:
1. Audio data is on the user side.
2. Audio data is on the audio library buffer (Oto).
3. Audio data being on the hardware buffer.

"Unplayed" sounds like 2 + 3. "Queued" sounds like 2. That's why I lean towards "queued". That being said, it's not a big deal as long as the documentation is clear, so feel free to go with whatever name you prefer.

**Comment by hajimehoshi** [comment]
>  "Queued" is a good alternative for referring to only 2. 

I'm not convinced that "Queued" is only for 2. Can this represent 3 technically?

**Comment by tinne26** [comment]
Yeah it can represent 3 technically, I agree with you there. But among the choices, "unplayed" is unambiguously including 3, while "queued" is somewhat ambiguous, but it can be more reasonably interpreted to cover only 2, as in "queued to be sent to the hardware audio buffer".

**Comment by hajimehoshi** [comment]
What about `BufferedSize()`?

**Comment by tinne26** [comment]
As long as we have `GetBufferSize()` accessible to do `GetBufferSize() - BufferedSize()`, seems good to me too.

**Comment by hajimehoshi** [comment]
OK I'll go with `BufferedSize`. Thanks!

**Comment by hajimehoshi** [comment]
6b6ed5248fb1958a60e7dc65a41eccabc4172bc9
