### ISSUE TITLE
Oto doesn't work on some Windows machines (44100hz)

### ISSUE THREAD

**Issue by quasilyte** [ebitengine/oto#221]
I'm still trying to collect more info, but I got some bug reports from the players that claim that the game doesn't run on Windows.
I wasn't able to reproduce it, but one of the players shared this info:

https://steamcommunity.com/app/2416030/eventcomments/3820795764942715398/?tscn=1693875357#c3820796140090974511

```
panic: oto: initialization failed: WASAPI: oto: the specified format is not supported (there is the closest format instead), WinMM: oto: device not found
```

Windows version is `Microsoft Windows [Version 10.0.19045.3324]`
Oto version used is `github.com/hajimehoshi/oto/v2 v2.4.0`

I'm not sure if this issue is fixed in the later oto release, since I can't reproduce this crash. :)

I requested the sound hardware info details from the user.

The closest thing I've found is this issue:
https://github.com/ebitengine/oto/issues/215
But it was about 48000hz; could it be related to the 44100hz as well?

**Comment by hajimehoshi** [comment]
Yeah, I think this is already fixed in the main branch at #215. So, would it be possible to test the main branch of Oto and Ebitengine? If this works, I'll consider to backport the fix.

**Comment by quasilyte** [comment]
Yes, it should be possible to test.
I'll create an open "beta" game branch in Steam to ask the player to test whether it's any different.
I'll report back when any new info is available.

**Comment by hajimehoshi** [comment]
> go: upgraded github.com/hajimehoshi/oto/v2 v2.4.0 => v2.4.1

v2.4.1 doesn't include the fix unfortunately. You'd need to test Ebitengine v2.6.0-alpha.6 or something.

**Comment by quasilyte** [comment]
Ah, I see.
I'll do this then:
```
$ go get github.com/hajimehoshi/ebiten/v2@main
go: upgraded github.com/ebitengine/purego v0.3.2 => v0.5.0-alpha.1
go: upgraded github.com/hajimehoshi/bitmapfont/v3 v3.0.0-alpha => v3.0.0
go: upgraded github.com/hajimehoshi/ebiten/v2 v2.5.0-alpha.12.0.20230228174701-7c0fbce0cfd8 => v2.6.0-alpha.6.0.20230903172145-20ddfba98368
go: upgraded golang.org/x/image v0.8.0 => v0.11.0
go: upgraded golang.org/x/mobile v0.0.0-20230531173138-3c911d8e3eda => v0.0.0-20230818142238-7088062f872d
go: upgraded golang.org/x/sys v0.9.0 => v0.11.0
go: upgraded golang.org/x/text v0.10.0 => v0.12.0

$ go mod tidy
go: downloading github.com/ebitengine/oto/v3 v3.1.0-alpha.2
```
So, it's Ebitengine `v2.6.0-alpha.6.0.20230903172145-20ddfba98368` and Oto `v3.1.0-alpha.2`

**Comment by hajimehoshi** [comment]
Yeah, this should include the fix. Thanks!

**Comment by hajimehoshi** [comment]
I think this was resolved.
