### ISSUE TITLE
How to "Linked Frameworks and Libraries" when I don't use Xcode project?

### ISSUE THREAD

**Issue by arthurspa** [ebitengine/oto#223]
I'm writing an app using https://github.com/fyne-io/fyne and https://github.com/faiface/beep (which uses Oto for playing).
When I target Mac it works as expected. However it crashes when I target to iOS.
Then I realise that I've missed this step of "Linked Frameworks and Libraries".

How to do that when I don't have a Xcode project? It's a pure go project.

Thanks.

**Comment by hajimehoshi** [comment]
beep uses Oto v1, so I don't recommend using this. Oto v1 is no longer maintained.

**Comment by hajimehoshi** [comment]
> How to do that when I don't have a Xcode project? It's a pure go project.

`-framework` flags might work.

**Comment by hajimehoshi** [comment]
> How to do that when I don't have a Xcode project? It's a pure go project.

Oto v1 is NOT purego.

**Comment by arthurspa** [comment]
Thanks for quick reply, @hajimehoshi .
I see. For iO, even in latest release of OTO, it still requires the frameworks `AVFoundation.framework` and `AudioToolbox.framework`, according to the docs.
My question remains, how do I link those frameworks without using XCode IDE since I don't have a XCode project?

**Comment by hajimehoshi** [comment]
I'm afraid I have no idea to build iOS libraries without Xcode
