### ISSUE TITLE
How to play consecutive audio files with different sample rates

### ISSUE THREAD

**Issue by mark-summerfield** [ebitengine/oto#227]
Suppose I have two audio files one with a sample rate of 44100 and the other with 48000.
I can't see how I can play one after the other since once I create an oto.Context with a specific sample rate I can't change the context _or_ the sample rate.
I tried along these lines:
```go
if format.SampleRate != sampleRate {
    sampleRate = format.SampleRate
    otoCtx = nil
    runtime.GC()
    otoCtx = ... with new context options including the new sample rate
}
```
but this just crashed with `oto: context is already created`.

**Comment by hajimehoshi** [comment]
Unfortunately there is no way to change the sample rate. This seems duplicated with #149

**Comment by mark-summerfield** [comment]
OK, thanks.

**Comment by Asday** [comment]
Consider remuxing your input streams to the highest sample rate among them (in realtime if you like), and using that sample rate for the context.
