### ISSUE TITLE
Windows 11 WSL build error context.go undefined: newDriver

### ISSUE THREAD

**Issue by pfarrell51** [ebitengine/oto#231]
go build
# github.com/hajimehoshi/oto
../../../../go/pkg/mod/github.com/hajimehoshi/oto@v1.0.1/context.go:69:12: undefined: newDriver

This is on WSL Windows 11.
Do I need to specifically tell it which driver_linux.go to build?
or maybe tweak the go.mod file?

**Comment by hajimehoshi** [comment]
Specify GOOS=windows.

**Comment by pfarrell51** [comment]
thanks
that worked
