### ISSUE TITLE
[MacOS] Cannot run example. Hangs & nothing ever happens. Affects other libraries that use `oto/v3`.

### ISSUE THREAD

**Issue by atljoseph** [ebitengine/oto#233]
On an M1 Mac, with Sonoma 14.3.1. Cannot run tests, and cannot run example. Am using `beep` in golang, which imports this library, and it keeps hanging... `oto/v3` is the culprit. As soon as i removed the import to `oto/v3` from the example, it ran fine. Please fix this. I'm not even sure where to start, other than to say that this happens even when `CGO_ENABLED=1`. I have also signed the Xcode license, too, and ensured that Xcode tools are properly installed.

Link: https://github.com/gopxl/beep/issues/145#issuecomment-1974932659

**Comment by hajimehoshi** [comment]
Please let me know if this issue happens only with oto, without beep.

**Comment by atljoseph** [comment]
It’s all in the comment above, which states that the issue is with oto.
There is even a link to issue I created there. Got it working with a
different lib, although that lib is a bit painful.

**Comment by hajimehoshi** [comment]
So does this issue happen without beep?

**Comment by atljoseph** [comment]
![image](https://github.com/ebitengine/oto/assets/25017621/d0d647a5-0d6d-4749-a3a9-c76f15dd7349)

i’m not sure on why GitHub is so dang slow right now, but the message that shows whenever I click view, and GitHub is not the same message as when I go on my laptop and look at it. It has been updated. I updated it hours ago.

**Comment by hajimehoshi** [comment]
The code imports `github.com/gopxl/beep/speaker`. Again, does this issue happens only with oto?

**Comment by atljoseph** [comment]
I’m very thankful for your time and energy you spent on this repo. But, respectfully, I don’t think you even read what was posted. It doesn’t work out of the box for me. Not even the example. I spent time debugging it and tracked down most of the source. Please, please… ask intelligent questions. You wrote the lib, so I know the intelligence is there. Exercise it. Please.

**Comment by atljoseph** [comment]
To be very clear, I never even downloaded or looked at oto before trying to debug your repo. The issue happened in oto, but your code imports oto. So, yeah. I don’t need this crap or this code.

**Comment by hajimehoshi** [comment]
> Please, please… ask intelligent questions

You have never answred Yes or No to my questions. If this happens with beep, this is beep's responsibility, not Oto.

**Comment by atljoseph** [comment]
The answer to your question is already there in black-and-white. That’s why
I never answered yes or no because it was a dumb question. If you read what
I put in the picture… Oh my gosh. I’m glad I don’t know you. Goodbye.

**Comment by hajimehoshi** [comment]
Goodbye!

**Comment by atljoseph** [comment]
Good riddance. I see you have no time to be a person.

**Comment by atljoseph** [comment]
When you ask a yes, or no question after I already said, it was a problem
with the other repo, you’re just trying to gaslight somebody. You got some
personal issues to work out. I hope you get them worked out.

**Comment by hajimehoshi** [comment]
For future notes: In general, investigating an issue including an library's dependency (beep in this case) is not the original library (oto in this case) owner's task. As long as the issue doesn't happen only with the original library itself, the owner doesn't have any responsibility to investigate this.

**Comment by atljoseph** [comment]
Can you not see that I linked to an issue that I opened in the other
repository? For future reference, it will do you well to read and
comprehend before responding

**Comment by hajimehoshi** [comment]
> Can you not see that I linked to an issue that I opened in the other
> repository? 

I've already said:

> The code imports github.com/gopxl/beep/speaker. 

So this code depends on beep, and you have not created a minimal reproducible case only with Oto.

**Comment by MarkKremer** [comment]
He's asking you to try to reproduce the issue with oto without beep as a wrapper so that we can exclude beep being the culprit entirely. In your linked issue you seem to use oto through beep still.

**Comment by atljoseph** [comment]
I’m not sure how to respond to this bullshit

**Comment by atljoseph** [comment]
I already reproduced it, and explained how to, and posted the minimal
snippet that reproduced it for me, including information about environment,
variable, and what not. Please read the screenshot that I posted Jesus
Christ

**Comment by hajimehoshi** [comment]
I have read it. The answer is https://github.com/ebitengine/oto/issues/233#issuecomment-1975076058

**Comment by atljoseph** [comment]
You know, it’s not really even a big issue. I’ve already found other code
that works. The bigger issue is how you guys approach people that report
things.

**Comment by hajimehoshi** [comment]
I'm glad you have already found a solution or a workaround!

Maybe you don't understand the fact that Beep is just a wrapper of Oto. If you import `github.com/gopxl/beep/speaker`, this means that you use Beep and Oto at the same time, so we cannot say which is the culprit. And, investigating any dependencies like Beep is not Oto owner's responsibility. Probably you should continue this discussion at Beep's thread. https://github.com/gopxl/beep/issues/145#issuecomment-1974932659

**Comment by atljoseph** [comment]
I’m very proficient at Golang and software in general. I’m not a dumbass.

**Comment by atljoseph** [comment]
I actually can say, which one is the culprit. And I did so much earlier
tonight.

**Comment by hajimehoshi** [comment]
> So, The problem only ever shows up when oto is imported. It is hidden
> inside of speaker. By importing speaker, one imports oto implicitly.

So this might be an issue in Beep (or Speaker)'s wrong usage of Oto rather than Oto itself.

**Comment by atljoseph** [comment]
Why did it take so long? And so many messages to get the point across? I
already stated this stuff very obviously. It’s all in the screenshot

**Comment by hajimehoshi** [comment]
If you could create a reproducible case like

```go
import (
    _ "github.com/ebitengine/oto/v3"
)
```

this should be Oto's responsibility. But, as long as you import beep or speaker, we cannot say which is the culprit.

> That was the narrowed down to the speaker package importing oto. I copy
> pasted and repurposed a separate package from speaker and deleted all
> references to oto, and then magically logs started printing.

I don't understand what you meant by 'deleting' the reference. Could you show a complete code set to reproduce your issue?

**Comment by atljoseph** [comment]
It’s not my issue anymore. I’m not using your code. Nuff said. I don’t care
if you fix this or not.  I’ve spent enough of free time on this. Was able
to reproduce it directly in oto with their example. Hell, their tests won’t
even run. Go and check. It’s obvious that you don’t think I’m capable of
determining this

**Comment by hajimehoshi** [comment]
OK, case closed.

**Comment by atljoseph** [comment]
Maybe it has to do with Apple silicon

**Comment by hajimehoshi** [comment]
> Was able
> to reproduce it directly in oto with their example. Hell, their tests won’t
> even run. Go and check

I tested 

```
go run github.com/ebitengine/oto/v3/example@v3.1.0
```

and the example run on my MacBook M3 Pro. A new fix 401d95b9f0372c1f72fe1138be56e2d62ae7bb65 which will be released in a few days might change the situation, but I don't know.

**Comment by atljoseph** [comment]
Funny. I ended up using the audio player from your ebiten v2 repo. Didn’t
realize it was yours too (thanks for the pixie dust). A little wonky
probably due to the cross platform nature of things, but it worked for
sure. Would also prefer a channel to determine when playback has completed,
but eh. Interesting that this code imports oto v3 too. Same version. Not
sure why it would hang in one place and not in another. Def sounds like
usage, but hangs it does.

**Comment by atljoseph** [comment]
I hope you can find a way to forgive my disrespect tonight.

**Comment by hajimehoshi** [comment]
I don't mind. Thank you for using Oto and Ebitengine!
