### ISSUE TITLE
Build issue when cross-compiling on Windows for linux target: undefined: newContext

### ISSUE THREAD

**Issue by thrasher-** [ebitengine/oto#239]
When attempting to cross compile an app on a Windows host targeting linux, I get the following build error from oto@v3.2.0

```
$ GOOS=linux go build
# github.com/ebitengine/oto/v3
..\..\..\..\..\pkg\mod\github.com\ebitengine\oto\v3@v3.2.0\context.go:38:11: undefined: context
..\..\..\..\..\pkg\mod\github.com\ebitengine\oto\v3@v3.2.0\context.go:100:21: undefined: newContext
```

Compiling natively on Linux works fine however

**Comment by hajimehoshi** [comment]
Specify `CGO_ENABLED=1`.

**Comment by hajimehoshi** [comment]
Even with `CGO_ENABLED=1`, it might be impossible to cross-compile oto.
