### ISSUE TITLE
Linux build failed

### ISSUE THREAD

**Issue by ozorrilla** [ebitengine/oto#247]
I have built an application that plays music, using this library but when I try to build it for linux it fails using this command
```
CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=7 go build -a -o music -buildvcs=false
```
On the other hand, if I do it for windows it works perfectly
```
GOOS=windows GOARCH=amd64 go build -a -o music.exe -buildvcs=false
```
The error that occurs when I try to build it on linux is the following:
```
$ CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -a -o music -buildvcs=false
# github.com/ebitengine/oto/v3
vendor\github.com\ebitengine\oto\v3\context.go:38:11: undefined: context 
vendor\github.com\ebitengine\oto\v3\context.go:100:21: undefined: newContext
```

**Comment by hajimehoshi** [comment]
> CGO_ENABLED=0

Oto is not Cgo-free for Linux yet.
