### ISSUE TITLE
Expose multiple tracks to the OS (music/sound effects)

### ISSUE THREAD

**Issue by Seb-C** [ebitengine/oto#248]
Would it be possible to support having multiple output tracks and naming it?

I have seen games doing that, so that as a player, I could see multiple tracks of the same process in my OS sound settings, and configure it separately. I would like to use this to send the music and sound effects in two different contexts/tracks/playbacks (I don't know the correct name for this).

For example, any Youtuber or Streamer who records the game would have two different audio tracks in their video editors, and be able to remove/replace the music while keeping the sound effects.

That would be a big help since I want to use royalty-free musics (which usually triggers Content-ID copyright issues on Youtube).

I don't know if my understanding is correct, but I guess that it would require to allow multiple contexts and name them? Or would `Player` be the correct abstraction layer for this (are they always mixed by the process itself instead of the OS)?

**Comment by hajimehoshi** [comment]
Is this #54?

**Comment by Seb-C** [comment]
No, it's a different request.

**Comment by hajimehoshi** [comment]
>  Or would Player be the correct abstraction layer for this (are they always mixed by the process itself instead of the OS)?

Yes, if I understand your request correctly.
