### ISSUE TITLE
Data-Race Issue with Oto on Mac Mini (Apple M2)

### ISSUE THREAD

**Issue by kuroko-shirai** [ebitengine/oto#252]
When running the following code with the `-race` flag on a Mac Mini (Apple M2), a data-race issue occurs:

```go
otoCtx, readyChan, err := oto.NewContext(op)
if err != nil {
	panic("oto.NewContext failed: " + err.Error())
}
```

The issue is evident in the following screenshot:

![telegram-cloud-photo-size-2-5384120476726584147-y](https://github.com/user-attachments/assets/6adb02c8-4afb-4d3c-975e-b4352208a81a)

Fortunately, this issue can be easily resolved by modifying a single line in `driver_darwin.go` 

https://github.com/ebitengine/oto/blob/03f5f70bd121e0cbd0faedcf994f54955fa90e42/driver_darwin.go#L161

Changing the line to:

```
<-ready
```

ensures that the readiness is awaited. I have tested this solution and it works correctly in my case.

**Comment by hajimehoshi** [comment]
Thanks, fixed!
