### ISSUE TITLE
Oto test coverage

### ISSUE THREAD

**Issue by Noofbiz** [ebitengine/oto#68]
Headless testing of such a low level library might be impossible, or take a lot of work to get started. I'd like to explore getting some test coverage for oto. 
The biggest roadblock is testing the drivers without any actual sound cards available. There's a couple ways we could go about doing this. In the test, we could replace theContext's driverWriter with something like the following

```go
// stepPlayer is used for headless mode audio, such as for tests
// you can control exactly how many steps it takes which allows for verification
// of the PCM data written to it.
type stepPlayer struct {
	ThrowWriteError bool
	stepStart       chan []byte
	stepDone        chan struct{}
}

func (l *stepPlayer) Write(b []byte) (int, error) {
	if l.ThrowWriteError {
		return 0, errors.New("write error")
	}
	l.stepStart <- b
	<-l.stepDone

	return len(b), nil
}

func (l *stepPlayer) Close() error {
	return nil
}

func (l *stepPlayer) Bytes() []byte {
	return <-l.stepStart
}

func (l *stepPlayer) Step() {
	if len(l.stepDone) > 0 {
		return
	}
	l.stepDone <- struct{}{}
}
```

(this is what I replaced oto.Player with in engo to test it. All it does is take in the PCM data sent to the player and spit it back out.) This lets the tests check that data is actually being passed, and the tests can compare that data to what it expects. The upside is it should work, with build tags. The downside is that it wouldn't actually test any of the actual drivers, only the mock test driver would actually ever be tested. So coverage would be less than 100%.

Another alternative would be to create/use dummy drivers for testing. For example, ALSA has a loopback driver [here](https://www.alsa-project.org/wiki/Matrix:Module-aloop). If it could be setup on Travis, then this driver would take in data and spit it out, similar to above. This would have the added benefit of actually testing the driver code, so coverage could get to 100% (or at least pretty good!) There's also a node.js package [here](https://github.com/audiojs/web-audio-api). Not sure about windows/ios/mobile testing. I'll look around and see.

**Comment by hajimehoshi** [comment]
Dummy drivers for testing sound the way to go so far.
